export const SUGGESTIONS: Record<string, string[]> = {
  'Coding & Development': [
    "Create a python script to scrape a website",
    "Build a React dashboard for IoT devices",
    "Develop a full-stack Next.js app with Firebase authentication",
    "Write a Bash script to automate daily backups",
    "Create a Chrome extension that summarizes articles",
    "Build a REST API using Node.js and Express",
    "Write a SQL query to analyze customer retention",
    "Develop a real-time chat application using WebSockets",
    "Create a responsive landing page using Tailwind CSS",
    "Build a machine learning model to predict house prices",
    "Write a unit test suite for a React component",
    "Develop a Discord bot using Python",
    "Create a simple CRUD application with Vue.js",
    "Build a personal portfolio website from scratch",
    "Write an algorithmic solution for a LeetCode hard problem",
    "Create a 2D platformer game using Godot",
    "Develop a mobile app using React Native for fitness tracking",
    "Build a serverless function using AWS Lambda",
    "Write a Go script to monitor server performance",
    "Create a Rust CLI tool for parsing JSON files"
  ],
  'Writing & Marketing': [
    "Write a cold email to a potential investor",
    "Create a content calendar for a month of social media posts",
    "Draft a press release for a new product launch",
    "Write a high-converting landing page copy for a SaaS product",
    "Create an SEO-optimized blog post about artificial intelligence",
    "Write a compelling product description for an e-commerce store",
    "Draft a LinkedIn post announcing a new job",
    "Create a brand voice guideline document",
    "Write a script for a 60-second YouTube Short",
    "Draft a persuasive newsletter for subscribers",
    "Create a pitch deck outline for a seed stage startup",
    "Write a detailed case study on customer success",
    "Draft a set of engaging tweet threads about productivity",
    "Create a compelling Instagram bio and content strategy",
    "Write a professional response to a negative customer review",
    "Draft a comprehensive marketing plan for Q3",
    "Create an engaging welcome email sequence",
    "Write a thought leadership article for Medium",
    "Draft an apology letter to customers for a service outage",
    "Create a list of 50 viral hook ideas for TikTok"
  ],
  'Research & Analysis': [
    "Analyze the latest trends in renewable energy",
    "Summarize the key findings of the latest IPCC climate report",
    "Compare the economic models of the top 3 tech giants",
    "Research the history of artificial intelligence from 1950 to present",
    "Explain the psychological mechanisms behind habit formation",
    "Analyze the impact of remote work on commercial real estate",
    "Compare different fasting protocols for longevity",
    "Research the geopolitical implications of the semiconductor industry",
    "Explain the basics of quantum computing to a layman",
    "Analyze the success factors of top indie game developers",
    "Research the evolution of the English language over 500 years",
    "Explain the pros and cons of nuclear energy",
    "Analyze the strategy of the top 5 direct-to-consumer brands",
    "Research the most effective study techniques for medical students",
    "Explain the physiological effects of chronic stress",
    "Analyze the demographic shifts expected in the next 50 years",
    "Compare the educational systems of Finland and South Korea",
    "Research the potential applications of CRISPR in agriculture",
    "Explain the Fermi Paradox and its possible solutions",
    "Analyze the economic impact of universal basic income"
  ],
  'Image Generation': [
    "A neon-lit cyberpunk samurai frog in a rainy alleyway",
    "A photorealistic macro shot of a golden beetle on a leaf",
    "An isometric 3D render of a cozy coffee shop at night",
    "A cinematic landscape of a floating island in the clouds",
    "A portrait of a futuristic cyborg wearing high fashion",
    "An oil painting of a cat reading a book in a library",
    "A hyper-detailed concept art of a sci-fi spaceship interior",
    "A minimalist vector illustration of a mountain sunrise",
    "A surrealist digital painting of a clock melting in a desert",
    "A photorealistic image of a futuristic city underwater",
    "An anime-style background of a train station in summer",
    "A pencil sketch of an ancient ruin hidden in a dense jungle",
    "A 3D render of a cute robot holding a glowing flower",
    "A watercolor painting of a bustling market in Marrakesh",
    "A cinematic shot of a dragon breathing fire over a medieval castle",
    "A futuristic cyberpunk UI design for a holographic display",
    "A highly detailed photograph of a nebula in deep space",
    "A stylized low-poly illustration of a cozy winter cabin",
    "A majestic griffin soaring through a canyon at sunset",
    "A vibrant pop-art portrait of a 1920s jazz musician"
  ]
};
